config/routes.rb
Rails.application.routes.draw do
  # # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'sessions#welcome'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  delete '/logout' => 'sessions#destroy'

  get 'auth/google_oauth2/callback' => 'sessions#omniauth'
  get '/just_added' => 'shows#just_added'


  resources :shows, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :shows do 
    resources :notes, only: [:new, :create, :index, :show, :edit]
  end
  resources :notes
  resources :users, only: [:show]
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
    belongs_to :show, optional: true
    belongs_to :user, optional: true
    accepts_nested_attributes_for :show
    validates :content, presence: true

end

app/models/show.rb
class Show < ApplicationRecord 
    has_many :notes
    has_many :users, through: :notes
    validates :show_title, presence: true 
    accepts_nested_attributes_for :notes
    scope :just_added, -> { order(created_at: :desc).limit(3) }
end

app/models/user.rb
class User < ApplicationRecord
    has_many :notes
    has_many :shows, through: :notes
    validates :username, uniqueness: true,  presence: true
    validates :email, uniqueness: true, presence: true
    accepts_nested_attributes_for :notes
    has_secure_password

    def self.from_omniauth(auth)
        where(email: auth.info.email).first_or_initialize do |user|
          user.username = auth.info.name
          user.email = auth.info.email
          user.password = SecureRandom.hex
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?
  protect_from_forgery

  private

  def current_user
    @current_user ||= User.find_by_id(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!session[:user_id]
  end

  def redirect_if_not_logged_in
    redirect_to login_path if !logged_in?
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
    before_action :redirect_if_not_logged_in

    def index
      if @show = Show.find_by_id(params[:show_id])
        @notes = @show.notes
      else
        @notes = Note.all
      end
    end

    def new
      if @show = Show.find_by(id: params[:show_id])
          @note = @show.notes.build
      else
          @note = Note.new
      end
    end
    
    def create
      @note = current_user.notes.create!(note_params)
      if @note.save
        redirect_to show_note_path(@note.show, @note)
      else
        render :new
      end
   end


    def show
      @show = Show.find_by(id: params[:show_id])
      @note = Note.find_by_id(params[:id])
    end

    private

    def note_params
        params.require(:note).permit(:content, :show_id, :user_id, :status, show_attributes: :show_title)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def welcome
  end

  def destroy
    session.delete(:user_id)
    redirect_to '/'
  end

  def new
  end

  def create
    @user = User.find_by(username: params[:session][:username])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash[:error] = "Sorry, login was incorrect. Please try again."
      redirect_to login_path
    end
  end

  def omniauth
    @user = User.from_omniauth(auth)
    @user.save
    session[:user_id] = @user.id
    redirect_to user_path(@user)
  end

  private

  def auth
    request.env['omniauth.auth']
  end
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  before_action :redirect_if_not_logged_in

  def new 
    @show = Show.new
  end

  def create
    @show = Show.new(show_params.except(:note))
    # byebug
    if @show.save
      @note = Note.new(show_params[:note])
      @note.user_id = session[:user_id]
      @note.show_id = @show.id
      @note.save
      redirect_to show_path(@show)
    else
      render :new
    end
  end

  def show 
    @show = Show.find_by_id(params[:id])
  end
  
  def edit
    @show = Show.find(params[:id])
  end

  def destroy
    Show.find(params[:id]).destroy
    redirect_to shows_path
  end

  def update
    @show = Show.find(params[:id])
    @show.update(show_title: params[:show][:show_title])
    redirect_to show_path(@show)
  end

  def index
    if logged_in?
      @user = current_user
      @shows = current_user.shows.uniq
    end
  end

  def just_added
    if logged_in?
      @user = current_user
      @shows = current_user.shows.just_added.uniq
    end
  end

  private

  def show_params
    params.require(:show).permit(:show_title, :note_id, note: :content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def show
    @user = User.find_by_id(params[:id])
    if @user != current_user
      flash[:message] = "You can only view your own list."
      redirect_to user_path(current_user)
    end
  end

  private

  def user_params
      params.require(:user).permit(:username, :email, :password, note_attributes: :note_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
    def render_nav_bar
        if logged_in?
          render partial: 'layouts/loggedin_links'
        else
          render partial: 'layouts/loggedout_links'
        end
    end
end	

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(object.errors.count, "error") %>
      prohibited this from being saved:
    </h2>
 
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_loggedin_links.html.erb
<%= link_to "Log Out", logout_path, method: :delete %> |
<%= link_to "Add a Show", new_show_path %> |
<%= link_to "All Shows", shows_path %> |

app/views/layouts/_loggedout_links.html.erb
<%= link_to "Login", login_path %> |
<%= link_to "Signup", signup_path %> |
<%= link_to "Sign in with Github", "/auth/github" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
  <head>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1" />
    <link href="https://fonts.googleapis.com/css?family=Quicksand:400,600&display=swap" rel="stylesheet">

    <title>CouchPotato</title>

    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

    <link rel="stylesheet" href="/stylesheets/main.css"/>
    </head>

   

  <body>
    <div class="wrapper">
     <header><center>
     <img src="/images/banner.png" alt="CouchPotato Header" class="img-responsive main-image"></center>
     </header>

 <div align="right"><%= render_nav_bar %></div>

 <%= yield %> 

    <footer class="branding">
      <small>&copy; 2019 <strong>CouchPotato</strong></small>
      </footer>
    </div>

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
    <!--[if lt IE 7]>
      <script src="//ajax.googleapis.com/ajax/libs/chrome-frame/1.0.2/CFInstall.min.js"></script>
      <script>window.attachEvent("onload",function(){CFInstall.check({mode:"overlay"})})</script>
    <![endif]-->
  </body>
</html>

app/views/notes/edit.html.erb
<h1><%= @note.show.show_title%></h1>
<p><%= @note.content%></p>

app/views/notes/index.html.erb
<h1>Notes for <%= @show.show_title%></h1>
<% if @notes.count == 0 %>
  <h4>You haven't written any notes about this show yet.</h4>
<% else %>
<ul>
<% @notes.each do |n| %>
  <li>
    <%= n.content %>
    <%= n.status %>
  </li>
<% end %>
</ul>
<% end %>
<%= link_to "Add Note", new_show_note_path(@show.id) %><br>

app/views/notes/new.html.erb
<h1>Add a Note for <%= @show.show_title %></h1>

<%= render partial: 'layouts/errors', locals: {object: @note} %>

<%= form_for @note do |f| %>
<%= f.hidden_field :show_id, :value => params[:show_id] %>

    <%= f.label :content %>
    <%= f.text_area :content, size: "25x10" %>
    
    <%= f.select(:status, options_for_select([['Watched', "Watched"], ['To-Watch', "To-Watch"], ['Watching', "Watching"]])) %>

<%= f.submit "Add Note" %>
    </div>
<% end %>

app/views/notes/show.html.erb
<%= @note.content %><br>
<%= @note.status %>

app/views/shows/edit.html.erb
<h2>Show you are editing:<%= @show.show_title %></h2>
<%= form_for(@show) do |f| %> 
  <div>
    <%= f.label :show_title %>
    <%= f.text_field :show_title %><br>
  </div>
  <%= f.submit %> 
    <% end %>
<%= button_to "Delete", show_path(@show), method: :delete, data: { confirm: "Really?" } %><br>
<p>Go back to your <a href="/shows">watchlist</a>.</p>

app/views/shows/index.html.erb
<h1>Welcome, <%= @user.username %>!</h1><br>
<h2>Your Watchlist:</h2>
<%= link_to "Sort shows by date added", just_added_path %><br><br>
   <% @shows.each do |s| %>
   <h4><li><%= link_to s.show_title, show_path(s.id) %></h4>
    <%= link_to "Show Notes", show_notes_path(s.id) %> - <%= link_to "Edit Show", edit_show_path(s.id) %><br><br>
<% end %>
<p>Add a new show <%= link_to "here.", new_show_path %></p>

app/views/shows/just_added.html.erb
<h2>Your Watchlist by most recently added:</h2>

   <% @shows.each do |s| %>
   <h4><li><%= link_to s.show_title, show_path(s.id) %></h4>
    <p><%= link_to "Show Notes", show_notes_path(s.id) %>
<% end %>

app/views/shows/new.html.erb
<h2>Add a show you want to watch:</h2>

<%= render partial: 'layouts/errors', locals: {object: @show} %>

  <%= form_for Show.new do |f| %> 
  <div>
    <%= f.label :show_title %>
    <%= f.text_field :show_title %><br>
  </div>
  <div>
    <%=f.fields_for :note do |b| %>
      <%= b.label :content %>
      <%= b.text_area :content %>
    <% end %>
  </div>
  <br>

    <%= f.submit %>
  <% end %>

app/views/shows/show.html.erb
<%= @show.show_title %></h2><br>
<%= link_to "Edit", edit_show_path %><br>
<%= link_to "Add Note", new_show_note_path(@show.id) %><br>

app/views/users/new.html.erb
 <h1>Sign up</h1>

 <%# <%= render partial: 'layouts/errors', locals: {object: @user} %>

  <%= form_for(@user, url: signup_path) do |f| %> 

    <%= f.label :username %>
    <%= f.text_field :username %><br>

    <%= f.label :email %>
    <%= f.email_field :email%><br>

    <%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.submit "Sign Up", class: "btn btn-primary" %>
  <% end %>
  <br>
<p>I'm already a CouchPotato <%= link_to "User", login_path %></a>.</p>
  </div>
</div>

app/views/users/show.html.erb
<h1>Welcome, <%= @user.username %>!</h1><br>
<h4><%= link_to "Go to your watchlist", shows_path %></h4>